library(ggpomological)
library(tarchetypes)
library(conflicted)
library(patchwork)
library(tidyverse)
library(lubridate)
library(targets)
library(scales)
library(ggmap)
library(sf)
library(fs)

conflict_prefer("filter", "dplyr")
