library(ggpomological)
library(tarchetypes)
library(conflicted)
library(patchwork)
library(tidyverse)
library(lubridate)
library(showtext)
library(targets)
library(scales)
library(ggmap)
library(sf)
library(fs)

showtext_auto()
conflict_prefer("filter", "dplyr")

font_add_google("Schoolbell", "bell")
